baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Reformat"

# disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
disableKinds = ["RSS", "taxonomyTerm"]

copyright = "Reformat Web Development Ltd"

[params]
  description = "Development for design studios"

[imagesizes]
  sm = 375
  md = 768
  lg = 1280

[imaging]
  quality = 88

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = -100

  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = -90

  [[menu.main]]
    identifier = "company"
    name = "Company"
    url = "/company/"
    weight = -80

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -70